Repository 7Cav/cScripts, pull requests merged in 2018-09, with the labels that each got.

#180 Added 2/B/1-7 Platoon and squad patches
  cScripts/CavFnc/functions/selections/fn_initInsigniaSelections.sqf
  cScripts/CfgUnitInsignia.hpp
  cScripts/Data/Insignia/1-2-B-17.paa
  cScripts/Data/Insignia/2-B-17.paa
Labels: enhancement

#178 Added check for already added labels for the label module
  cScripts/CavFnc/functions/modules/fn_moduleApplyVehicleLable.sqf
Labels: enhancement

#172 Alpha loadout update
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/CavFnc/functions/selections/fn_initQuickSelections.sqf
  cScripts/Loadouts/CfgLoadouts_Alpha.hpp
  cScripts/Loadouts/CfgLoadouts_Common.hpp
Labels: enhancement

#182 Update for McGehee merged with current build
  cScripts/CavFnc/functions/init/fn_initCuratorObjectPlaced.sqf
  cScripts/CavFnc/functions/init/fn_initVehicle.sqf
  cScripts/Data/Vehicles/McGehee/Mortar_McGehee_camo_Green.paa
  cScripts/Data/Vehicles/McGehee/Mortar_McGehee_ceremonial_black.paa
Labels: enhancement

#181 Settings changes
  cba_settings.sqf
Labels: enhancement

#187 Adjusted tool
  tools/build.py
Labels: enhancement, ignore changelog

#194 Update to internal build version 4.2.10
  cScripts/script_component.hpp
Labels: ignore changelog
