Repository 7Cav/cScripts, pull requests merged in 2018-10, with the labels that each got.

#196 Updated Cba Settings
  cba_settings.sqf
Labels: enhancement, needs approval, under review

#189 Added B-2-A-1/7 insignia
  cScripts/CavFnc/functions/selections/fn_initInsigniaSelections.sqf
  cScripts/CfgUnitInsignia.hpp
  cScripts/Data/Insignia/B-2-A-17.paa
Labels: enhancement

#185 Removed weird comment
  cScripts/CavFnc/CfgFunctions.hpp
Labels: cleanup

#186 Cleanup and quality of life update
  cScripts/CavFnc/functions/documents/fn_Doc_Info.sqf
  cScripts/CavFnc/functions/documents/fn_Doc_MissionControl.sqf
  cScripts/CavFnc/functions/init/fn_initModules.sqf
  cScripts/CavFnc/functions/texture/fn_getVehicleLable.sqf
  cScripts/CavFnc/functions/texture/fn_setVehicleLable.sqf
  cScripts/Loadouts/script/CfgPoppy.hpp
Labels: cleanup, enhancement

#195 Weapons now only safe and never unsafe when obtaining gear
  cScripts/CavFnc/functions/systems/fn_setPostInitPlayerSettings.sqf
Labels: enhancement

#183 Added our own addObjectToCurator function.
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/modules/fn_moduelCreateFieldHospital.sqf
  cScripts/CavFnc/functions/modules/fn_moduelCreateMedicalCrate.sqf
  cScripts/CavFnc/functions/modules/fn_moduelCreateSpecialWeaponsCrate.sqf
  cScripts/CavFnc/functions/modules/fn_moduelCreateSupplyCrate.sqf
  cScripts/CavFnc/functions/systems/fn_addObjectToCurator.sqf
Labels: enhancement

#184 Added new system to handle vehicle loadouts
  cScripts/CavFnc/cScripts_preInit.sqf
  cScripts/CavFnc/functions/init/fn_initVehicle.sqf
  cScripts/CavFnc/functions/systems/fn_setVehicleInventory.sqf
Labels: enhancement

#188 Player in game rank is set based on name prefix
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/cScripts_postInit.sqf
  cScripts/CavFnc/cScripts_preInit.sqf
  cScripts/CavFnc/functions/systems/fn_doPlayerAnnouncement.sqf
  cScripts/CavFnc/functions/systems/fn_getPlayerRank.sqf
  cScripts/CavFnc/functions/systems/fn_setPlayerRank.sqf
  cScripts/CavFnc/functions/systems/fn_setPreInitPlayerSettings.sqf
Labels: enhancement

#191 Updated alpha loadouts
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/CavFnc/functions/selections/fn_initQuickSelections.sqf
  cScripts/Loadouts/CfgLoadouts_Alpha.hpp
  cScripts/Loadouts/CfgLoadouts_Common.hpp
Labels: enhancement

#197 Adjustments and fixes to modules
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/init/fn_initModules.sqf
  cScripts/CavFnc/functions/modules/fn_moduleCreateFieldHospital.sqf
  cScripts/CavFnc/functions/modules/fn_moduleCreateMedicalCrate.sqf
  cScripts/CavFnc/functions/modules/fn_moduleCreateSpecialWeaponsCrate.sqf
  cScripts/CavFnc/functions/modules/fn_moduleCreateStarterCrate.sqf
  cScripts/CavFnc/functions/modules/fn_moduleCreateSupplyCrate.sqf
  cScripts/CavFnc/functions/systems/fn_addObjectToCurator.sqf
Labels: enhancement

#199 Adjusted ranger Loadouts
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/Loadouts/CfgLoadouts_Ranger.hpp
Labels: enhancement, loadouts

#202 Fixed indent in configs
  cScripts/CfgUnitInsignia.hpp
  cScripts/Loadouts/CfgLoadouts_Alpha.hpp
  cScripts/ViewingDistance/CfgFunctions.hpp
Labels: cleanup

#200 Fixed config style checker
  tools/config_style_checker.py
Labels: ignore changelog

#204 Combat cameraman s5
  cScripts/CfgLoadouts.hpp
  cScripts/Loadouts/CfgLoadouts_S5.hpp
Labels: enhancement

#201 Fixed engineer not set due to being bool instead of number
  cScripts/CavFnc/functions/systems/fn_setPreInitPlayerSettings.sqf
  cScripts/Loadouts/CfgLoadouts_Alpha.hpp
  cScripts/Loadouts/CfgLoadouts_AlphaClass.hpp
  cScripts/Loadouts/CfgLoadouts_Bravo.hpp
  cScripts/Loadouts/CfgLoadouts_Charlie.hpp
  cScripts/Loadouts/CfgLoadouts_Common.hpp
  cScripts/Loadouts/CfgLoadouts_Medical.hpp
  cScripts/Loadouts/CfgLoadouts_S3.hpp
  cScripts/Loadouts/CfgLoadouts_Training.hpp
Labels: bugfix

#205 Version Update 4.2.11
  cScripts/script_component.hpp
Labels: ignore changelog

#207 Added B_AssaultPack_cbr to ranger crate
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
Labels: enhancement

#212 Version update for internal build
  cScripts/script_component.hpp
Labels: ignore changelog

#210 Fixed issues with ranger loadouts not loaded.
  cScripts/Loadouts/CfgLoadouts_Ranger.hpp
Labels: bugfix

#211 Fixed way back leftover typo were company were labeled as platoon.
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/logistics/fn_doStarterCrate.sqf
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/CavFnc/functions/modules/fn_moduleCreateStarterCrate.sqf
  cScripts/CavFnc/functions/selections/fn_initQuickSelections.sqf
  cScripts/CavFnc/functions/systems/fn_addQuickSelection.sqf
  cScripts/CavFnc/functions/systems/fn_getCompanyVariable.sqf
  cScripts/CavFnc/functions/systems/fn_hasCompanyVariable.sqf
  cScripts/CavFnc/functions/systems/fn_setPreInitPlayerSettings.sqf
Labels: cleanup

#208 Endex and debug fixes
  cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf
  cScripts/CavFnc/functions/systems/fn_setPreInitPlayerSettings.sqf
Labels: bugfix, enhancement

#213 Update README.md
  README.md
Labels: ignore changelog

#214 Update README.md
  README.md
Labels: ignore changelog

#215 Update README.md
  README.md
Labels: ignore changelog
