Repository 7Cav/cScripts, pull requests merged in 2019-11, with the labels that each got.

#485 Remove Ace Canteen
  cScripts/Loadouts/CfgLoadouts_Alpha.hpp
  cScripts/Loadouts/CfgLoadouts_Bravo.hpp
  cScripts/Loadouts/CfgLoadouts_Common.hpp
Labels: enhancement

#483 Added none to error check
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
Labels: bugfix

#490 Create test.yml
  .github/workflows/testing.yml
  tools/sqf_validator.py
Labels: ignore changelog

#492 Update testing.yml
  .github/workflows/testing.yml
Labels: ignore changelog

#493 Update testing.yml
  .github/workflows/testing.yml
Labels: ignore changelog

#489 Remove Ranger/Sniper
  cScripts/CavFnc/functions/helpers/fn_exportLoadoutsToArsenal.sqf
  cScripts/CavFnc/functions/init/fn_initStartupHint.sqf
  cScripts/CavFnc/functions/logistics/fn_doStarterCrate.sqf
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/CavFnc/functions/modules/fn_moduleCreateStarterCrate.sqf
  cScripts/CavFnc/functions/players/fn_getRadioChannel.sqf
  cScripts/CavFnc/functions/players/fn_getSquadInsignia.sqf
  cScripts/CavFnc/functions/systems/fn_addArsenal.sqf
  cScripts/CavFnc/functions/systems/fn_addInsigniaSelectionList.sqf
  cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf
  cScripts/CfgLoadouts.hpp
  cScripts/Loadouts/CfgLoadouts_Common.hpp
  cScripts/Loadouts/CfgLoadouts_Ranger.hpp
  cScripts/Loadouts/CfgLoadouts_RangerClass.hpp
  tools/build.ini
Labels: cleanup, enhancement, loadouts
