Repository 7Cav/cScripts, pull requests merged in 2019-09, with the labels that each got.

#463 Fortification take2
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/cScripts_postInit.sqf
  cScripts/CavFnc/cScripts_preInit.sqf
  cScripts/CavFnc/functions/init/fn_initFortify.sqf
  cScripts/CavFnc/functions/players/fn_setPreInitPlayerSettings.sqf
  cScripts/CavFnc/functions/systems/fn_addFortifyArea.sqf
  initServer.sqf
Labels: enhancement

#465 Quick selection variable error
  cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf
Labels: bugfix

#459 Updated public settings
  tools/build.ini
Labels: enhancement

#456 Updated and adjusted structure
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/documents/fn_Doc_Info.sqf
  cScripts/CavFnc/functions/players/fn_getRadioChannel.sqf
  cScripts/CavFnc/functions/players/fn_getSquadInsignia.sqf
  cScripts/CavFnc/functions/players/fn_getSquadName.sqf
Labels: cleanup, enhancement

#466 Improvements to squad naming and channel system
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/documents/fn_Doc_Info.sqf
  cScripts/CavFnc/functions/players/fn_getRadioChannel.sqf
  cScripts/CavFnc/functions/players/fn_getSquadInsignia.sqf
  cScripts/CavFnc/functions/players/fn_getSquadName.sqf
  cScripts/CavFnc/functions/players/fn_setRadioChannel.sqf
  cScripts/CavFnc/functions/systems/fn_getChannelName.sqf
Labels: enhancement

#470 Comp update
  Compositions/Cav_Lancer_Deployment/composition.sqe
  Compositions/Cav_Lancer_Deployment/header.sqe
  Compositions/Cav_Viking_Platoon_Deployment_D/composition.sqe
  Compositions/Cav_Viking_Platoon_Deployment_D/header.sqe
  Compositions/Cav_Viking_Platoon_Deployment_W/composition.sqe
  Compositions/Cav_Viking_Platoon_Deployment_W/header.sqe
Labels: compositions, enhancement

#467 Modifications for new vehicles from RHS update.
  cScripts/CavFnc/functions/init/fn_initVehicle.sqf
  cScripts/CavFnc/functions/modules/fn_moduleApplyVehicleInventory.sqf
  cScripts/CavFnc/functions/systems/fn_setVehicleInventory.sqf
  cScripts/CavFnc/functions/systems/fn_setVehicleSettings.sqf
Labels: enhancement

#469 Cavalry scout loadouts
  cScripts/Loadouts/CfgLoadouts_Bravo.hpp
  cScripts/Loadouts/CfgLoadouts_BravoClass.hpp
  cScripts/Loadouts/CfgLoadouts_Common.hpp
Labels: enhancement, loadouts

#471 Fixed classes missing class
  cScripts/Loadouts/CfgLoadouts_BravoClass.hpp
Labels: enhancement

#473 Fixed Viking composition
  Compositions/Cav_Viking_Platoon_Deployment_D/composition.sqe
  Compositions/Cav_Viking_Platoon_Deployment_W/composition.sqe
Labels: bugfix, compositions, critical

#474 Fixed param expecting string instead of object
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/CavFnc/functions/players/fn_getSquadName.sqf
Labels: bugfix, critical
