Repository 7Cav/cScripts, pull requests merged in 2019-07, with the labels that each got.

#403 Removed left over macro
  cScripts/script_macros.hpp
Labels: cleanup

#401 Removed Common old
  cScripts/Loadouts/CfgLoadouts_Common.old.hpp
Labels: cleanup

#398 Converted init to add settings
  cScripts/CavFnc/cScripts_preInit.sqf
Labels: enhancement

#404 Announchment not shown propperly
  cScripts/CavFnc/functions/players/fn_doPlayerAnnouncement.sqf
Labels: bugfix

#399 Setting to handle zeus immortality
  cScripts/CavFnc/cScripts_preInit.sqf
  cScripts/CavFnc/functions/players/fn_setPreInitPlayerSettings.sqf
  cScripts/Loadouts/CfgLoadouts_S3.hpp
Labels: enhancement

#400 Updated setting as for July
  cba_settings.sqf
Labels: enhancement

#406 Update fn_moduleCallEndex.sqf
  cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf
Labels: enhancement

#402 Added unarmed unit
  cScripts/Loadouts/CfgLoadouts_Training.hpp
Labels: enhancement, loadouts

#397 ReGear should now run on local client
  cScripts/CavFnc/functions/modules/fn_moduleRegearTrooper.sqf
Labels: bugfix

#413 player referenced instead of param unit
  cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf
Labels: bugfix

#415 Added Special insignias to selector
  cScripts/CavFnc/functions/selections/fn_initInsigniaSelections.sqf
Labels: enhancement

#414 Added spray to staff, squads and alpha bravo FTL
  cScripts/Loadouts/CfgLoadouts_Charlie.hpp
  cScripts/Loadouts/CfgLoadouts_CharlieClass.hpp
Labels: enhancement, loadouts

#417 Clan check functions
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/players/fn_getPlayerClan.sqf
  cScripts/CavFnc/functions/players/fn_getPlayerName.sqf
  cScripts/CavFnc/functions/players/fn_isPlayerClan.sqf
  cScripts/CavFnc/functions/players/fn_setPlayerRank.sqf
  cScripts/script_component.hpp
Labels: enhancement

#412 Re added charlie inventory
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
Labels: enhancement

#419 Hot fixed endex causing issues on holdFireMessage
  cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf
Labels: bugfix

#427 Doc ignore
  .gitignore
  tools/build.ini
Labels: ignore changelog

#428 Only check the cscripts script folder
  .travis.yml
Labels: ignore changelog

#374 Date topic removed from diary records
  cScripts/CavFnc/functions/documents/fn_DocChklist_CFF.sqf
  cScripts/CavFnc/functions/documents/fn_DocChklist_JMTASKS.sqf
  cScripts/CavFnc/functions/documents/fn_DocChklist_LZEXTRACT.sqf
  cScripts/CavFnc/functions/documents/fn_DocChklist_LZINSERT.sqf
  cScripts/CavFnc/functions/documents/fn_DocChklist_LZSPECS.sqf
  cScripts/CavFnc/functions/documents/fn_DocRadio_LACEACE.sqf
  cScripts/CavFnc/functions/documents/fn_DocRadio_MEDEVAC.sqf
  cScripts/CavFnc/functions/documents/fn_DocRadio_ROTARYPICKUP.sqf
  cScripts/CavFnc/functions/documents/fn_DocRadio_SPOTREP.sqf
  cScripts/CavFnc/functions/documents/fn_Doc_Info.sqf
  cScripts/CavFnc/functions/documents/fn_Doc_MissionControl.sqf
Labels: enhancement

#421 Adjustments to endex script
  cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf
Labels: bugfix, enhancement

#423 Added new ACRE settings
  cba_settings.sqf
Labels: enhancement

#420 Updated TAWVD
  README.md
  cScripts/ViewingDistance/CfgFunctions.hpp
  cScripts/ViewingDistance/GUI.h
  cScripts/ViewingDistance/defines.h
  cScripts/ViewingDistance/fn_onChar.sqf
  cScripts/ViewingDistance/fn_onSavePressed.sqf
  cScripts/ViewingDistance/fn_onSaveSelectionChanged.sqf
  cScripts/ViewingDistance/fn_onSliderChanged.sqf
  cScripts/ViewingDistance/fn_onTerrainChanged.sqf
  cScripts/ViewingDistance/fn_openMenu.sqf
  cScripts/ViewingDistance/fn_openSaveManager.sqf
  cScripts/ViewingDistance/fn_stateTracker.fsm
  cScripts/ViewingDistance/fn_updateViewDistance.sqf
Labels: enhancement

#429 Documentation function
  tools/generate_wiki_articles.py
Labels: ignore changelog

#430 Revert "Date topic removed from diary records"
  cScripts/CavFnc/functions/documents/fn_DocChklist_CFF.sqf
  cScripts/CavFnc/functions/documents/fn_DocChklist_JMTASKS.sqf
  cScripts/CavFnc/functions/documents/fn_DocChklist_LZEXTRACT.sqf
  cScripts/CavFnc/functions/documents/fn_DocChklist_LZINSERT.sqf
  cScripts/CavFnc/functions/documents/fn_DocChklist_LZSPECS.sqf
  cScripts/CavFnc/functions/documents/fn_DocRadio_LACEACE.sqf
  cScripts/CavFnc/functions/documents/fn_DocRadio_MEDEVAC.sqf
  cScripts/CavFnc/functions/documents/fn_DocRadio_ROTARYPICKUP.sqf
  cScripts/CavFnc/functions/documents/fn_DocRadio_SPOTREP.sqf
  cScripts/CavFnc/functions/documents/fn_Doc_Info.sqf
  cScripts/CavFnc/functions/documents/fn_Doc_MissionControl.sqf
Labels: ignore changelog

#432 Changed announcement handler
  cScripts/CavFnc/functions/players/fn_doPlayerAnnouncement.sqf
Labels: enhancement

#424 Added support for cav vehicles for vic settings
  cScripts/CavFnc/functions/systems/fn_setVehicleInventory.sqf
  cScripts/CavFnc/functions/systems/fn_setVehicleSettings.sqf
Labels: enhancement

#436 Fixed endex not executing on everyclient
  cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf
Labels: bugfix

#437 Fixed html not shown
  tools/generate_wiki_articles.py
Labels: ignore changelog
