Repository 7Cav/cScripts, pull requests merged in 2020-06, with the labels that each got.

#607 Fixed spelling and added additional checks and logging
  cScripts/CavFnc/cScripts_preInit.sqf
  cScripts/CavFnc/functions/init/fn_initACELoadouts.sqf
  cScripts/CavFnc/functions/init/fn_initTagging.sqf
  cScripts/CavFnc/functions/init/fn_initVehicle.sqf
  cScripts/CavFnc/functions/players/fn_setActiveRadio.sqf
  cScripts/CavFnc/functions/players/fn_setPlayerRank.sqf
  cScripts/CavFnc/functions/players/fn_setTeamColor.sqf
Labels: T-Cleanup, T-Enhancement, T-Settings

#608 Added classname export tool
  tools/export_classnames.py
Labels: ignore changelog

#610 Made endex less spammy
  cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf
Labels: T-Enhancement

#611 Added Gunslinger radio protocol
  cScripts/CavFnc/functions/players/fn_getRadioChannel.sqf
Labels: T-Enhancement

#609 Fixed atlas
  cScripts/CavFnc/functions/players/fn_getRadioChannel.sqf
  cScripts/CfgLoadouts.hpp
  cScripts/Loadouts/CfgLoadouts_Bravo.hpp
  cScripts/Loadouts/CfgLoadouts_BravoClass.hpp
  cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp
  cScripts/Loadouts/CfgLoadouts_Bravo_Scouts.hpp
Labels: T-Cleanup, T-Enhancement, T-Loadouts

#613 Various fixes
  cScripts/CavFnc/cScripts_preInit.sqf
  cScripts/CavFnc/functions/init/fn_initModules.sqf
  cScripts/CavFnc/functions/players/fn_getPlayerRank.sqf
  cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf
  cScripts/CavFnc/functions/players/fn_setPreInitPlayerSettings.sqf
  cScripts/Loadouts/CfgLoadouts_Bravo_Scouts.hpp
Labels: T-Bugfix, T-Enhancement

#616 Fixed Crash
  cScripts/CavFnc/functions/systems/fn_getVehicleLable.sqf
Labels: T-Bugfix

#617 Fixed missing semicolon
  cScripts/CavFnc/functions/init/fn_initFortify.sqf
Labels: T-Bugfix

#622 Atlas fixes
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf
  cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp
Labels: T-Loadouts, needs approval [bravo]

#620 Updated build and settings
  cba_settings.sqf
  tools/build_settings_config.sh
Labels: T-Enhancement, T-Settings, WIP

#619 Update fn_getVehicleLable.sqf
  cScripts/CavFnc/functions/systems/fn_getVehicleLable.sqf
Labels: T-Bugfix

#623 Fixed build script
  tools/build.ini
  tools/build.py
Labels: ignore changelog

#624 Fixed atlas not being bravo
  cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf
Labels: T-Bugfix

#625 Update README.md
  README.md
Labels: ignore changelog

#626 fix spawn with empty magazine loaded - Mag Well system
  cScripts/Loadouts/script/CfgFunctions.hpp
  cScripts/Loadouts/script/functions/main/fn_findLoadableWeapon.sqf
  cScripts/Loadouts/script/functions/main/fn_getMagwellMagazines.sqf
Labels: T-Bugfix, T-Enhancement

#627 Updated CBA settings
  cba_settings.sqf
Labels: T-Enhancement, T-Settings

#629 Diary show if you are med or eng trained
  cScripts/CavFnc/functions/documents/fn_Doc_Info.sqf
Labels: T-Enhancement

#628 Ignoring changes to debug
  .gitignore
Labels: ignore changelog
