Repository 7Cav/cScripts, pull requests merged in 2020-07, with the labels that each got.

#632 ACE arsenal update
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/helpers/fn_exportLoadoutContentToArsenal.sqf
  cScripts/CavFnc/functions/helpers/fn_exportLoadoutToArsenal.sqf
  cScripts/CavFnc/functions/init/fn_initACELoadouts.sqf
  cScripts/Loadouts/CfgLoadouts_Alpha.hpp
  cScripts/Loadouts/CfgLoadouts_AlphaClass.hpp
  cScripts/Loadouts/CfgLoadouts_Bravo.hpp
  cScripts/Loadouts/CfgLoadouts_BravoClass.hpp
  cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp
  cScripts/Loadouts/CfgLoadouts_Charlie.hpp
  cScripts/Loadouts/CfgLoadouts_CharlieClass.hpp
  cScripts/Loadouts/CfgLoadouts_Common.hpp
  cScripts/Loadouts/CfgLoadouts_S3.hpp
  cScripts/Loadouts/CfgLoadouts_S5.hpp
  cScripts/Loadouts/CfgLoadouts_Training.hpp
  cScripts/Loadouts/CfgLoadouts_TrainingClass.hpp
  tools/build.py
Labels: T-Cleanup, T-Enhancement, T-Loadouts

#637 Jump and getout updates
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/mission/fn_addGetOutHelo.sqf
  cScripts/CavFnc/functions/mission/fn_addJump.sqf
  cScripts/CavFnc/functions/systems/fn_doGetOutHeloLeft.sqf
  cScripts/CavFnc/functions/systems/fn_doGetOutHeloRight.sqf
  cScripts/CavFnc/functions/systems/fn_doGetOutHeloSide.sqf
  cScripts/CavFnc/functions/systems/fn_setVehicleSettings.sqf
Labels: T-Enhancement

#638 FIxed abilities not being shown in diary record
  cScripts/CavFnc/functions/documents/fn_Doc_Info.sqf
Labels: T-Bugfix

#633 cleanup texture and unused functionaloity
  cScripts/CavFnc/functions/init/fn_initSupply.sqf
  cScripts/CavFnc/functions/init/fn_initVehicle.sqf
  cScripts/CavFnc/functions/logistics/fn_doEmptyCrate.sqf
  cScripts/CavFnc/functions/logistics/fn_doSupplyCrate.sqf
  cScripts/Data/Objects/Ammobox_7CAV_co.paa
  cScripts/Data/Objects/Flag_7CAV_00.paa
  cScripts/Data/Objects/Flag_7CAV_01.paa
  cScripts/Data/Objects/Flag_7CAV_02.paa
  cScripts/Data/Vehicles/McGehee/Mortar_McGehee_camo_Green.paa
  cScripts/Data/Vehicles/McGehee/Mortar_McGehee_ceremonial_black.paa
Labels: T-Cleanup, T-Enhancement

#630 Added moduel add to alive
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/cScripts_preInit.sqf
  cScripts/CavFnc/functions/init/fn_initModules.sqf
  cScripts/CavFnc/functions/modules/fn_moduleAddToAlive.sqf
Labels: T-Enhancement

#644 server diagnostics action
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf
  cScripts/CavFnc/functions/systems/fn_getServerMetrics.sqf
Labels: T-Enhancement

#640 Delete junk around starter crate (fn_deleteDroppedObjects)
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/logistics/fn_doStarterCrate.sqf
  cScripts/CavFnc/functions/systems/fn_deleteDroppedObjects.sqf
Labels: T-Enhancement

#641 Blake update to loadouts
  cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp
Labels: T-Bugfix, T-Enhancement, T-Loadouts

#647 Fixed warning being info
  cScripts/CavFnc/functions/debug/fn_logWarning.sqf
Labels: T-Bugfix
