Repository 7Cav/cScripts, pull requests merged in 2020-01, with the labels that each got.

#411 Changed safety lock function to ace function
  cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf
Labels: T-Enhancement

#517 ACE release fixes
  cScripts/CavFnc/functions/init/fn_initModules.sqf
  cScripts/CavFnc/functions/systems/fn_addHeal.sqf
  cScripts/Loadouts/script/functions/atomics/fn_replaceItems.sqf
  cba_settings.sqf
Labels: T-Enhancement, T-Settings

#518 Fixes to settings
  cba_settings.sqf
Labels: T-Enhancement, T-Settings

#520 Added user to author detection
  tools/generate_wiki_articles.py
Labels: ignore changelog

#524 Cleaning in the startercrate
  cScripts/CavFnc/functions/logistics/fn_doStarterCrate.sqf
Labels: T-Cleanup, T-Enhancement

#523 Moved cav scout under bravo base
  cScripts/Loadouts/CfgLoadouts_Common.hpp
Labels: T-Enhancement, T-Loadouts

#521 Updated Export function
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/helpers/fn_exportContainerToArsenal.sqf
  cScripts/CavFnc/functions/helpers/fn_exportLoadoutsToArsenal.sqf
Labels: T-Enhancement

#519 Added splint to medical crate
  cScripts/CavFnc/functions/logistics/fn_doMedicalCrate.sqf
Labels: T-Enhancement

#525 Updated and rewrote cav arsenal containers
  cScripts/CavFnc/functions/systems/fn_addArsenal.sqf
Labels: T-Enhancement

#530 Adjusted loadouts to fit a 343
  cScripts/Loadouts/CfgLoadouts_Charlie.hpp
Labels: T-Loadouts

#532 Changed settings
  cba_settings.sqf
Labels: T-Settings

#529 Fixed path
  cScripts/CavFnc/functions/systems/fn_addHeal.sqf
Labels: T-Enhancement

#522 Updated vehicle inventory
  cScripts/CavFnc/functions/systems/fn_setVehicleInventory.sqf
Labels: T-Enhancement, T-Loadouts

#527 Added item replacement system
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/cScripts_postInit.sqf
  cScripts/CavFnc/cScripts_preInit.sqf
  cScripts/CavFnc/functions/init/fn_initItemReplace.sqf
  cba_settings.sqf
Labels: T-Enhancement, T-Settings

#533 fixed typo
  cScripts/CavFnc/functions/init/fn_initItemReplace.sqf
Labels: T-Enhancement

#538 Fixed comma
  cScripts/CavFnc/functions/systems/fn_setVehicleInventory.sqf
Labels: T-Enhancement

#539 fixed usage of old variable
  cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf
Labels: T-Enhancement

#540 Fixed missing semicolon (bad linter!)
  cScripts/CavFnc/functions/systems/fn_setVehicleInventory.sqf
Labels: T-Enhancement

#542 fixed errors in script
  cScripts/CavFnc/functions/systems/fn_setVehicleInventory.sqf
Labels: T-Enhancement

#543 Open ACRE Zeus Settings
  cba_settings.sqf
Labels: T-Enhancement, T-Settings

#547 Fix Saw Ammo for Bravo Loadouts
  cScripts/CavFnc/functions/init/fn_initACELoadouts.sqf
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/CavFnc/functions/logistics/fn_doSupplyCrate.sqf
  cScripts/CavFnc/functions/systems/fn_addArsenal.sqf
  cScripts/Loadouts/CfgLoadouts_Bravo.hpp
Labels: T-Enhancement, T-Loadouts

#550 Item replace and build update
  cScripts/CavFnc/functions/init/fn_initItemReplace.sqf
  tools/build.ini
Labels: T-Enhancement, T-Public

#536 Updated medical settings
  cba_settings.sqf
Labels: T-Settings

#555 Fixed some script headers
  cScripts/CavFnc/functions/debug/fn_logError.sqf
  cScripts/CavFnc/functions/debug/fn_logInfo.sqf
  cScripts/CavFnc/functions/debug/fn_logWarning.sqf
  cScripts/CavFnc/functions/init/fn_initStartupHint.sqf
Labels: T-Cleanup, T-Enhancement

#556 Added lancer to getSquadName
  cScripts/CavFnc/functions/players/fn_getSquadName.sqf
Labels: T-Enhancement

#559 Possible fixed 343 not active
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/players/fn_setActiveRadio.sqf
  cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf
  cScripts/CavFnc/functions/players/fn_setRadioChannel.sqf
Labels: T-Bugfix, T-Enhancement
