Repository 7Cav/cScripts, pull requests merged in 2020-03, with the labels that each got.

#574 Adding range table to mortar team leader
  cScripts/Loadouts/CfgLoadouts_Charlie.hpp
Labels: T-Enhancement, T-Loadouts

#573 Bravo loadouts
  cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf
  cScripts/Loadouts/CfgLoadouts_Bravo.hpp
  cScripts/Loadouts/CfgLoadouts_BravoClass.hpp
  cScripts/Loadouts/CfgLoadouts_Common.hpp
Labels: T-Enhancement, T-Loadouts

#575 Added wiki link to article
  tools/generate_wiki_articles.py
Labels: ignore changelog

#576 Fixed documentation script headers
  cScripts/CavFnc/functions/players/fn_hasCompanyVariable.sqf
Labels: T-Enhancement

#535 Update script_macros.hpp
  cScripts/script_macros.hpp
Labels: T-Enhancement

#537 Removed out supply crates functions and gear macros
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/logistics/fn_doAmmoCrate.sqf
  cScripts/CavFnc/functions/logistics/fn_doExplosivesCrate.sqf
  cScripts/CavFnc/functions/logistics/fn_doGrenadesCrate.sqf
  cScripts/CavFnc/functions/logistics/fn_doLaunchersCrate.sqf
  cScripts/CavFnc/functions/logistics/fn_doSpecialWeaponsCrate.sqf
  cScripts/CavFnc/functions/logistics/fn_doWeaponsCrate.sqf
  cScripts/CavFnc/functions/script_component.hpp
  cScripts/script_gearDefines.hpp
Labels: T-Cleanup, T-Enhancement

#577 Fixed classname issue
  cScripts/Loadouts/CfgLoadouts_CharlieClass.hpp
Labels: T-Bugfix

#579 Add 2/2/B Patch
  cScripts/CavFnc/functions/systems/fn_addInsigniaSelectionList.sqf
Labels: T-Enhancement

#580 Fixed gearfiles
  tools/build.ini
Labels: ignore changelog

#582 Cba Medical Updated
  cba_settings.sqf
Labels: T-Enhancement, T-Settings

#585 Minor readme formating
  README.md
Labels: ignore changelog
