Repository 7Cav/cScripts, pull requests merged in 2021-04, with the labels that each got.

#707 Updated and fixed para system
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/gear/fn_gear_setupRadios.sqf
  cScripts/CavFnc/functions/mission/fn_addHaloJump.sqf
  cScripts/CavFnc/functions/mission/fn_addLineJump.sqf
  cScripts/CavFnc/functions/systems/fn_para_backpack.sqf
  cScripts/CavFnc/functions/systems/fn_para_equipment.sqf
  cScripts/CavFnc/functions/systems/fn_para_haloJump.sqf
  cScripts/CavFnc/functions/systems/fn_para_lineJump.sqf
Labels: T-Enhancement

#705 added alpha patches
  cScripts/CavFnc/functions/systems/fn_addInsigniaSelectionList.sqf
Labels: T-Enhancement

#701 Fixed script not working and moved it to correct cat
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/gear/fn_gear_applyLoadout.sqf
  cScripts/CavFnc/functions/mission/fn_addLoadoutAction.sqf
  cScripts/CavFnc/functions/systems/fn_addLoadoutAction.sqf
Labels: T-Bugfix

#712 Tripod
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/Loadouts/CfgLoadouts_Charlie_Weapon.hpp
Labels: T-Enhancement, T-Loadouts

#710 Mortar loadout update
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
Labels: T-Enhancement, T-Loadouts

#716 Removed announcment system
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/cScripts_postInit.sqf
  cScripts/CavFnc/functions/players/fn_doPlayerAnnouncement.sqf
Labels: T-Enhancement

#715 Updated moduel checks and added missing setting
  cScripts/CavFnc/cScripts_postInit.sqf
  cScripts/CavFnc/cScripts_preInit.sqf
Labels: T-Enhancement

#714 Fixed syntax
  cScripts/CavFnc/functions/gear/fn_gear_postInit.sqf
  cScripts/CavFnc/functions/players/fn_setPlayerRank.sqf
Labels: T-Cleanup, T-Enhancement

#719 Remove ACEX Fortify Systems
  cScripts/CavFnc/cScripts_preInit.sqf
  cScripts/CavFnc/functions/systems/fn_addArsenal.sqf
  cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp
  cba_settings.sqf
Labels: T-Cleanup, T-Enhancement

#721 Fixed halo jump not working propperly
  cScripts/CavFnc/functions/systems/fn_checkVehicle.sqf
  cScripts/CavFnc/functions/systems/fn_para_backpack.sqf
  cScripts/CavFnc/functions/systems/fn_setVehicleSettings.sqf
Labels: T-Enhancement
