Repository 7Cav/cScripts, pull requests merged in 2021-05, with the labels that each got.

#731 removed armake
  .github/workflows/deploy.yml
Labels: ignore changelog

#734 Improved and made the logging system easy
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/debug/fn_diag_dumpPlayer.sqf
  cScripts/CavFnc/functions/debug/fn_logError.sqf
  cScripts/CavFnc/functions/debug/fn_logInfo.sqf
  cScripts/CavFnc/functions/debug/fn_logWarning.sqf
  cScripts/CavFnc/functions/depricated/fn_addAceCategory.sqf
  cScripts/CavFnc/functions/depricated/fn_logError.sqf
  cScripts/CavFnc/functions/depricated/fn_logInfo.sqf
  cScripts/CavFnc/functions/depricated/fn_logWarning.sqf
  cScripts/CavFnc/functions/diag/fn_error.sqf
  cScripts/CavFnc/functions/diag/fn_info.sqf
  cScripts/CavFnc/functions/diag/fn_log.sqf
  cScripts/CavFnc/functions/diag/fn_warning.sqf
Labels: T-Enhancement

#735 New icon system for loadout slections
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/systems/fn_getIcon.sqf
  cScripts/CavFnc/functions/systems/fn_setupLoadoutCategories.sqf
  cScripts/CavFnc/functions/systems/fn_setupLoadoutSelection.sqf
  cScripts/Loadouts/CfgLoadouts_Bravo_Viking.hpp
  cScripts/Loadouts/CfgLoadouts_Charlie_Squad.hpp
  cScripts/Loadouts/CfgLoadouts_Charlie_Weapon.hpp
  cScripts/Loadouts/CfgLoadouts_Common.hpp
Labels: T-Enhancement

#736 Added icons to items lost
  cScripts/CavFnc/functions/systems/fn_para_equipment.sqf
Labels: T-Enhancement

#737 Varrius cleanups
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/functions/gear/fn_gear_setupRadios.sqf
  cScripts/CavFnc/functions/systems/fn_addInsigniaSelectionList.sqf
  cScripts/CavFnc/functions/systems/fn_para_backpack.sqf
Labels: T-Enhancement

#738 cba and debug menu whitelist
  description.ext
Labels: T-Enhancement

#739 Fix Tripod adding bug
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
Labels: T-Enhancement, T-Loadouts

#742 Added radio debug and fixed some minor format
  cScripts/CavFnc/functions/depricated/fn_logError.sqf
  cScripts/CavFnc/functions/depricated/fn_logInfo.sqf
  cScripts/CavFnc/functions/depricated/fn_logWarning.sqf
  cScripts/CavFnc/functions/diag/fn_error.sqf
  cScripts/CavFnc/functions/diag/fn_info.sqf
  cScripts/CavFnc/functions/diag/fn_log.sqf
  cScripts/CavFnc/functions/diag/fn_warning.sqf
  cScripts/CavFnc/functions/documents/fn_Doc_Info.sqf
  cScripts/CavFnc/functions/documents/fn_Doc_Radio.sqf
  cScripts/CavFnc/functions/gear/fn_gear_applyLoadout.sqf
  cScripts/CavFnc/functions/gear/fn_gear_postInit.sqf
  cScripts/CavFnc/functions/gear/fn_gear_setupRadios.sqf
  cScripts/CavFnc/functions/init/fn_initStaging.sqf
  cScripts/CavFnc/functions/players/fn_setRadioChannel.sqf
Labels: T-Enhancement
