Repository 7Cav/cScripts, pull requests merged in 2022-06, with the labels that each got.

#835 Update cba_settings.sqf
  cba_settings.sqf
Labels: T-Settings

#833 Added ability to ignore NVG drop
  cScripts/functions/systems/fn_para_equipment.sqf
  cScripts/functions/systems/fn_para_haloJump.sqf
Labels: T-Enhancement, feature request

#831 Added debugging personal
  description.ext
Labels: ignore changelog
