Repository 7Cav/cScripts, pull requests merged in 2023-06, with the labels that each got.

#878 Updated validity item check
  cScripts/functions/logistics/fn_checkItemValidity.sqf
Labels: T-Enhancement

#875 Fixed S3 insignia being wrongly referenced
  cScripts/functions/systems/fn_addInsigniaSelectionList.sqf
Labels: T-Bugfix

#881 Fixed bug with check and array not being avalible
  cScripts/functions/mission/fn_addLoadoutAction.sqf
Labels: T-Bugfix

#877 Medical crate rework
  cScripts/CfgFunctions.hpp
  cScripts/cScripts_preInit.sqf
  cScripts/functions/init/fn_init_zenModuels.sqf
  cScripts/functions/logistics/fn_checkItemValidity.sqf
  cScripts/functions/logistics/fn_doFieldHospital.sqf
  cScripts/functions/logistics/fn_doMedicalCrate.sqf
  cScripts/functions/logistics/fn_getMedicalCrate.sqf
  cScripts/functions/modules/fn_zenModule_createMedicalCrate.sqf
  cScripts/functions/modules/fn_zenModule_rekitVehicle.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
Labels: T-Enhancement

#885 Fixed variable and fixed dubble quote
  cScripts/functions/systems/fn_getArsenalWhitelist.sqf
  cScripts/functions/vehicle/fn_vehicle_addPylonLoadout.sqf
Labels: T-Enhancement, T-Bugfix

#889 Fixed warning for bad class colon
  cScripts/Loadouts/CfgLoadouts_Alpha.hpp
  cScripts/Loadouts/CfgLoadouts_Alpha_FixedWing.hpp
  cScripts/Loadouts/CfgLoadouts_Alpha_Rotary.hpp
  cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp
  cScripts/Loadouts/CfgLoadouts_Bravo_Crew.hpp
  cScripts/Loadouts/CfgLoadouts_Bravo_Viking.hpp
  cScripts/Loadouts/CfgLoadouts_Charlie_Squad.hpp
  cScripts/Loadouts/CfgLoadouts_Charlie_Weapon.hpp
  cScripts/Loadouts/CfgLoadouts_Common.hpp
  cScripts/Loadouts/CfgLoadouts_UserCustom.hpp
Labels: T-Bugfix

#888 updated script
  tools/config_style_checker.py
  tools/search_privates.py
  tools/search_undefinedFunctions.py
Labels: ignore changelog

#892 Changed default decal on the medical vehicles
  cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
Labels: T-Enhancement

#891 Updated compositions
  Compositions/Cav_Bandit_Platoon_Deployment/composition.sqe
  Compositions/Cav_Bandit_Platoon_Deployment/header.sqe
  Compositions/Cav_Fixed_Wing_Aviation/composition.sqe
  Compositions/Cav_Fixed_Wing_Aviation/header.sqe
  Compositions/Cav_JTAC_Addon/composition.sqe
  Compositions/Cav_JTAC_Addon/header.sqe
  Compositions/Cav_Misfit_Platoon_Deployment/composition.sqe
  Compositions/Cav_Misfit_Platoon_Deployment/header.sqe
  Compositions/Cav_Rotary_Aviation/composition.sqe
  Compositions/Cav_Rotary_Aviation/header.sqe
  Compositions/Cav_S3_Mission_Controller/composition.sqe
  Compositions/Cav_S3_Mission_Controller/header.sqe
  Compositions/Cav_Stryker_Scout_Platoon/composition.sqe
  Compositions/Cav_Stryker_Scout_Platoon/header.sqe
Labels: T-Compositions

#897 Bug fixes for release candidate
  cScripts/functions/logistics/fn_createCargoCrate.sqf
  cScripts/functions/modules/fn_zenModule_createMedicalCrate.sqf
  cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
  cScripts/functions/vehicle/fn_vehicle_applyTextures.sqf
Labels: T-Enhancement, T-Bugfix

#898 Charlie-Compositons-Vehicle-Updated
  Compositions/Cav_Bandit_Platoon_Deployment/composition.sqe
  Compositions/Cav_Bandit_Platoon_Deployment/header.sqe
  Compositions/Cav_Misfit_Platoon_Deployment/composition.sqe
Labels: T-Compositions

#905 Adjust ammo in stryker dragoon
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
Labels: T-Enhancement

#906 Stryker Dragoon Temp Composition
  Compositions/Cav_Stryker_Scout_Platoon/composition.sqe
  Compositions/Cav_Stryker_Scout_Platoon/header.sqe
Labels: experimental, T-Compositions

#903 Fix viking slot order
  Compositions/Cav_Stryker_Scout_Platoon/composition.sqe
  Compositions/Cav_Stryker_Scout_Platoon/header.sqe
Labels: T-Compositions

#907 Update slotting order and composition
  Compositions/Cav_Stryker_Scout_Platoon/composition.sqe
  Compositions/Cav_Stryker_Scout_Platoon/header.sqe
Labels: T-Enhancement

#908 fix MG loadout and ACE IR Strobes
  cScripts/Loadouts/CfgLoadouts_Bravo_Viking.hpp
Labels: T-Enhancement

#910 Create release.yml
  .github/release.yml
Labels: ignore changelog

#911 Update HMMWV vehicle supplies and add SOCOM to faction list
  cScripts/cScripts_preInit.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
Labels: T-Enhancement

#909 Added check to check for array maulformation
  cScripts/functions/testing/fn_testing_loadoutArrays.sqf
Labels: T-Enhancement

#915 Fixed spelling error in stryker Anti-Air pylon
  cScripts/functions/vehicle/fn_vehicle_getPylon.sqf
  cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf
Labels: T-Bugfix

#916 Fixed typeName syntax in fn_testing_loadoutArrays
  cScripts/functions/testing/fn_testing_loadoutArrays.sqf
Labels: T-Bugfix
