Repository 7Cav/cScripts, pull requests merged in 2023-07, with the labels that each got.

#925 Add USAF to faction list
  cScripts/cScripts_preInit.sqf
Labels: T-Settings

#928 Set vehicles that have medical inventories as ACE medical vehicles
  cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
Labels: T-Enhancement

#920 Fixed incorrect grenades and magazines in HMMWV loadouts
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
Labels: T-Bugfix

#924 Changed Callsign from INFIDEL to CHAOS
  Compositions/Cav_JTAC_Addon/composition.sqe
Labels: T-Compositions

#923 Fixed issues with functions, crates and cosmetics not working on Zeus spawned vehicles.
  cScripts/CfgFunctions.hpp
  cScripts/functions/init/fn_init_vehicle.sqf
  cScripts/functions/systems/fn_isValidFaction.sqf
  cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
  cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
  cScripts/functions/vehicle/fn_vehicle_addPylonLoadout.sqf
  cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf
  cScripts/functions/vehicle/fn_vehicle_setRadio.sqf
  cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf
Labels: T-Enhancement, T-Bugfix, needs testing

#930 Improved create cargo crate code quality
  cScripts/functions/logistics/fn_createCargoCrate.sqf
Labels: T-Enhancement, T-Cleanup

#914 Added ability to rename crate
  cScripts/CfgFunctions.hpp
  cScripts/functions/logistics/fn_createCargoCrate.sqf
  cScripts/functions/systems/fn_renameObject.sqf
Labels: T-Enhancement, needs testing

#938 Missing then added
  cScripts/functions/logistics/fn_createCargoCrate.sqf
Labels: T-Bugfix, ignore changelog

#929 Changed medical crate module to use remote execution
  cScripts/functions/modules/fn_zenModule_createMedicalCrate.sqf
Labels: T-Bugfix

#939 Update build scripts
  .github/workflows/deploy.yml
Labels: ignore changelog

#945 Added Stryker Dragoon compatibility
  cScripts/cScripts_preInit.sqf
  cScripts/functions/vehicle/fn_vehicle_addCosmeticSelection.sqf
  cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
  cScripts/functions/vehicle/fn_vehicle_addPylonLoadout.sqf
  cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf
Labels: T-Enhancement, T-Vehicle

#943 Cleaned up and fixed formating and naming
  cScripts/functions/modules/fn_zenModule_callEndex.sqf
  cScripts/functions/players/fn_getPlayerRank.sqf
  cScripts/functions/players/fn_setPlayerRank.sqf
  cScripts/functions/players/fn_setTeamColor.sqf
Labels: T-Enhancement, T-Cleanup

#942 Made vehicle variables globaly broadcasted
  cScripts/functions/vehicle/fn_vehicle_addCosmeticSelection.sqf
  cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
  cScripts/functions/vehicle/fn_vehicle_addFlagAction.sqf
  cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
  cScripts/functions/vehicle/fn_vehicle_addRadio.sqf
  cScripts/functions/vehicle/fn_vehicle_applyLoadout.sqf
Labels: T-Enhancement

#940 Added function to clear and reset a vehicle
  cScripts/CfgFunctions.hpp
  cScripts/functions/mission/fn_addGetOutHelo.sqf
  cScripts/functions/mission/fn_addHaloJump.sqf
  cScripts/functions/mission/fn_addLineJump.sqf
  cScripts/functions/vehicle/fn_vehicle_reset.sqf
Labels: T-Enhancement

#941 Renamed addPylonLoadout to addDefaultLoadout
  cScripts/CfgFunctions.hpp
  cScripts/functions/init/fn_init_vehicle.sqf
  cScripts/functions/vehicle/fn_vehicle_addDefaultLoadout.sqf
Labels: T-Enhancement

#946 Fixed arrays with trailing commas
  cScripts/functions/vehicle/fn_vehicle_addCosmeticSelection.sqf
  cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
Labels: T-Enhancement

#944 Improved the item filter function
  cScripts/functions/logistics/fn_checkItemValidity.sqf
Labels: T-Enhancement

#953 Updated Alpha Compositions
  Compositions/Cav_Fixed_Wing_Aviation/composition.sqe
  Compositions/Cav_Rotary_Aviation/composition.sqe
Labels: T-Compositions

#954 Updated Bravo Compositions
  Compositions/Cav_Stryker_Scout_Platoon/composition.sqe
  Compositions/Cav_Stryker_Scout_Platoon/header.sqe
Labels: T-Compositions

#952 Updated TACP/FAC Callsigns
  Compositions/Cav_JTAC_Addon/composition.sqe
  Compositions/Cav_JTAC_Addon/header.sqe
Labels: T-Enhancement

#947 Updated CBA Settings to match current state
  cba_settings.sqf
Labels: T-Settings

#879 Depricated scripts for cav scripts instead
  cScripts/functions/mission/fn_gate.sqf
  cScripts/functions/mission/fn_teleport.sqf
Labels: T-Enhancement, Require later CavAddon

#927 Added magazine replacement system to sets a preference to sertain mod
  cScripts/cScripts_preInit.sqf
  cScripts/functions/init/fn_init_aceItemReplace.sqf
Labels: T-Enhancement, WIP

#934 Made radio manipulations possible with both TFAR and ACRE
  cScripts/CfgFunctions.hpp
  cScripts/cScripts_preInit.sqf
  cScripts/functions/documents/fn_Doc_Info.sqf
  cScripts/functions/documents/fn_Doc_Radio.sqf
  cScripts/functions/gear/fn_gear_applyLoadout.sqf
  cScripts/functions/gear/fn_gear_setupRadios.sqf
  cScripts/functions/init/fn_init_zenModuels.sqf
  cScripts/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/functions/players/fn_getRadioChannel.sqf
  cScripts/functions/players/fn_getSquadName.sqf
  cScripts/functions/players/fn_setActiveRadio.sqf
  cScripts/functions/players/fn_setRadioChannel.sqf
  cScripts/functions/systems/fn_clearRadioIds.sqf
  cScripts/functions/systems/fn_filterUnitLoadout.sqf
  cScripts/functions/systems/fn_getChannelName.sqf
  cScripts/functions/systems/fn_getRadioBase.sqf
  cScripts/functions/systems/fn_setupLoadoutSelection.sqf
  cScripts/functions/vehicle/fn_vehicle_addRadio.sqf
  cScripts/functions/vehicle/fn_vehicle_setRadio.sqf
  cScripts/script_component.hpp
  init.sqf
  tools/config_NoRadio.json
  tools/deploy.sh
Labels: T-Enhancement

#951 Swap M252 with Mk6, add laser guided ammo
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
Labels: T-Arsenal & Supplies

#958 Added variable to stop adding of additional staging actions localy for clients
  cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf
Labels: T-Enhancement

#955 Fixed bug where zeus-placed vehicles were not properly initialized
  cScripts/functions/init/fn_init_vehicle.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
  cScripts/functions/vehicle/fn_vehicle_reset.sqf
Labels: T-Bugfix

#873 Added loadouts for training units
  cScripts/CfgLoadouts.hpp
  cScripts/Loadouts/CfgLoadouts_Training.hpp
  cScripts/functions/systems/fn_setupLoadoutCategories.sqf
Labels: T-Enhancement, T-Loadouts

#919 Added new system to handle inventories for vehicles and crates
  cScripts/CfgFunctions.hpp
  cScripts/cScripts_preInit.sqf
  cScripts/functions/init/fn_init_logistics.sqf
  cScripts/functions/logistics/fn_addCargo.sqf
  cScripts/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/functions/logistics/fn_doSupplyCrate.sqf
  cScripts/functions/logistics/fn_getMedicalCrate.sqf
  cScripts/functions/logistics/fn_logistics_getContainer.sqf
  cScripts/functions/mission/fn_doStarterCrate.sqf
  cScripts/functions/mission/fn_doSupplyCrate.sqf
  cScripts/functions/modules/fn_zenModule_createMedicalCrate.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
Labels: T-Enhancement, needs testing, T-Arsenal & Supplies

#963 Added AC-130 / HAMMER-1 to Fixed Wing Composition
  Compositions/Cav_Fixed_Wing_Aviation/composition.sqe
  Compositions/Cav_Fixed_Wing_Aviation/header.sqe
Labels: T-Compositions

#966 Small error fixes 4.5.0
  cScripts/functions/init/fn_init_aceItemReplace.sqf
  cScripts/functions/systems/fn_getArsenalWhitelist.sqf
  tools/config_noRadio.json
Labels: T-Cleanup

#967 Fixed database now handle arsenal whitelist
  cScripts/functions/init/fn_init_logistics.sqf
  cScripts/functions/logistics/fn_checkItemValidity.sqf
  cScripts/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/functions/systems/fn_getArsenalWhitelist.sqf
Labels: T-Enhancement, T-Arsenal & Supplies

#972 Mayor fixes and adjustments
  cScripts/Loadouts/CfgLoadouts_Training.hpp
  cScripts/functions/init/fn_init_eventHandlers.sqf
  cScripts/functions/init/fn_init_logistics.sqf
  cScripts/functions/init/fn_init_skillAdjustment.sqf
  cScripts/functions/init/fn_init_vehicle.sqf
  cScripts/functions/logistics/fn_createCargoCrate.sqf
  cScripts/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/functions/logistics/fn_setCargoAttributes.sqf
  cScripts/functions/vehicle/fn_vehicle_addDefaultLoadout.sqf
  cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
  cScripts/functions/vehicle/fn_vehicle_addPylonSelection.sqf
  cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf
  cScripts/functions/vehicle/fn_vehicle_applyLoadout.sqf
  cScripts/functions/vehicle/fn_vehicle_getPylon.sqf
  cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf
  cScripts/script_component.hpp
Labels: T-Enhancement, T-Bugfix, T-Cleanup, T-Arsenal & Supplies

#973 Fixed bugs and faulty equipment as well as vehicle init delay
  cScripts/CfgFunctions.hpp
  cScripts/functions/init/fn_init_logistics.sqf
  cScripts/functions/init/fn_init_vehicle.sqf
  cScripts/functions/logistics/fn_createCargoCrate.sqf
  cScripts/functions/systems/fn_renameObject.sqf
  cScripts/functions/testing/fn_testing_equipmentUsed.sqf
  cScripts/functions/testing/fn_testing_loadoutArrays.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
  cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf
Labels: T-Enhancement, T-Bugfix, T-Cleanup

#949 Removed UK3CB BAF items from all loadouts
  cScripts/Loadouts/CfgLoadouts_Alpha.hpp
  cScripts/Loadouts/CfgLoadouts_Alpha_FixedWing.hpp
  cScripts/Loadouts/CfgLoadouts_Alpha_Rotary.hpp
  cScripts/Loadouts/CfgLoadouts_Bravo_Viking.hpp
Labels: T-Loadouts
