Repository 7Cav/cScripts, pull requests merged in 2023-08, with the labels that each got.

#981 Added Turns fix for curator spawned vehicles not getting items
  cScripts/functions/init/fn_init_vehicle.sqf
Labels: T-Bugfix

#982 Fixed: wrong phenylephrine class name
  cScripts/functions/init/fn_init_logistics.sqf
Labels: T-Bugfix

#979 Fixed Typo in ability function removing the ability localy
  cScripts/functions/gear/fn_gear_applyAbilities.sqf
Labels: T-Bugfix

#984 Fixed duplicate removal of ace items moved container getter to a variable
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
Labels: T-Bugfix, T-Cleanup

#986 Fixed function not getting added and added check for added already
  cScripts/functions/init/fn_init_vehicle.sqf
Labels: T-Bugfix

#988 Get variable not set variable for zeus addons
  cScripts/functions/init/fn_init_vehicle.sqf
Labels: T-Bugfix

#980 Cleaned script_macros and added new logging
  cScripts/cScripts_postInit.sqf
  cScripts/cScripts_preInit.sqf
  cScripts/script_macros.hpp
  init.sqf
Labels: T-Enhancement, T-Cleanup

#987 Fixed issue with vehicles not geting items applied with new zeus units
  .github/workflows/testing.yml
  cScripts/Loadouts/CfgLoadouts_Training.hpp
  cScripts/cScripts_postInit.sqf
  cScripts/functions/init/fn_init_eventHandlers.sqf
  cScripts/functions/init/fn_init_vehicle.sqf
  cScripts/functions/vehicle/fn_vehicle_addFlagAction.sqf
  cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
  cScripts/functions/vehicle/fn_vehicle_addPylonSelection.sqf
  cScripts/functions/vehicle/fn_vehicle_applyLoadout.sqf
  cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf
  cScripts/script_macros.hpp
  tools/lookForDebug.sh
Labels: T-Enhancement, T-Bugfix, T-Cleanup

#978 Changed atlas loadouts to be medic role as well as moved to top baseclass
  cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp
Labels: T-Enhancement, T-Cleanup

#990 Fixed startercreate items not getting added
  cScripts/cScripts_preInit.sqf
  cScripts/functions/init/fn_init_logistics.sqf
  cScripts/functions/logistics/fn_doStarterCrate.sqf
  cScripts/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/functions/logistics/fn_doSupplyCrate.sqf
  cScripts/functions/logistics/fn_logistics_getContainer.sqf
  cScripts/functions/mission/fn_addBaseCrate.sqf
  cScripts/functions/mission/fn_doStarterCrate.sqf
  cScripts/functions/systems/fn_getArsenalWhitelist.sqf
  cScripts/functions/vehicle/fn_vehicle_addPylonSelection.sqf
Labels: T-Bugfix, ignore changelog

#991 Update deploy.yml
  .github/workflows/deploy.yml
Labels: ignore changelog

#993 deploy fixes
  .github/workflows/deploy.yml
Labels: ignore changelog

#994 Fixed steps
  .github/workflows/deploy.yml
Labels: ignore changelog

#995 added main deploy
  .github/workflows/deploy.yml
  .github/workflows/deploy_main.yml
Labels: ignore changelog

#996 again!
  .github/workflows/deploy_main.yml
Labels: ignore changelog

#999 Fixed deploy
  .github/workflows/deploy.yml
Labels: ignore changelog

#1000 Updated deployment
  .github/workflows/deploy.yml
  .github/workflows/deploy_artifacts_main.yml
  .github/workflows/deploy_artifacts_tag.yml
  .github/workflows/deploy_main.yml
Labels: ignore changelog

#1002 Deploy one artifact file again...
  .github/workflows/deploy_artifacts_main.yml
  .github/workflows/deploy_artifacts_tag.yml
Labels: ignore changelog

#1003 Enabled ace_zeus_autoAddObjects for all clients
  cba_settings.sqf
Labels: T-Settings

#1004 Update deploy.yml
  .github/workflows/deploy.yml
Labels: ignore changelog

#1008 Make Fawk's NVG mod options optional
  cba_settings.sqf
Labels: T-Enhancement, ignore changelog

#1009 Fixed init issues with scripts as well as persistent adding of scripts and functionalities
  .github/workflows/testing.yml
  cScripts/CfgFunctions.hpp
  cScripts/cScripts_preInit.sqf
  cScripts/functions/gear/fn_gear_postInit.sqf
  cScripts/functions/init/fn_init_eventHandlers.sqf
  cScripts/functions/init/fn_init_vehicle.sqf
  cScripts/functions/logistics/fn_addCargo.sqf
  cScripts/functions/logistics/fn_createCargoCrate.sqf
  cScripts/functions/logistics/fn_doSupplyCrate.sqf
  cScripts/functions/mission/fn_addGetOutHelo.sqf
  cScripts/functions/mission/fn_addHaloJump.sqf
  cScripts/functions/mission/fn_addLineJump.sqf
  cScripts/functions/players/fn_setRadioChannel.sqf
  cScripts/functions/systems/fn_clearRadioIds.sqf
  cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
  cScripts/functions/vehicle/fn_vehicle_addDefaultLoadout.sqf
  cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
  cScripts/functions/vehicle/fn_vehicle_addFunctionsGlobal.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
  cScripts/functions/vehicle/fn_vehicle_addRadio.sqf
  cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf
  cScripts/functions/vehicle/fn_vehicle_setRadio.sqf
  description.ext
  init.sqf
  tools/checkDebug.sh
  tools/checkFixme.sh
  tools/checkLogging.sh
Labels: T-Enhancement, T-Bugfix, T-Cleanup

#1010 Updated bravo whitelist and alpha loadout fixes
  cScripts/Loadouts/CfgLoadouts_Alpha.hpp
  cScripts/Loadouts/CfgLoadouts_Alpha_FixedWing.hpp
  cScripts/Loadouts/CfgLoadouts_Alpha_Rotary.hpp
  cScripts/functions/init/fn_init_logistics.sqf
  cScripts/functions/systems/fn_getArsenalWhitelist.sqf
  cScripts/functions/systems/fn_setupLoadoutCategories.sqf
Labels: T-Loadouts, T-Arsenal & Supplies

#1011 Removed ACRE and TFAR radios in the ItemValidity
  cScripts/functions/logistics/fn_checkItemValidity.sqf
Labels: T-Enhancement

#1006 Added tfar auto join channel settings
  cba_settings.sqf
Labels: T-Settings

#1018 added wip lable test to block merge on wip tag
  .github/workflows/pull_request.yml
Labels: ignore changelog

#1021 Unit tests and database now use isEqualType instead of typeName
  cScripts/functions/init/fn_init_logistics.sqf
  cScripts/functions/testing/fn_testing_loadoutArrays.sqf
Labels: T-Enhancement

#1016 Added macro to make getContainer easier to read
  cScripts/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/functions/logistics/fn_doSupplyCrate.sqf
  cScripts/functions/systems/fn_getArsenalWhitelist.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
  cScripts/script_macros.hpp
Labels: T-Enhancement, T-Cleanup

#1013 Disabled renaming of cargo possible vehicles globaly
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
Labels: T-Bugfix

#1014 Disabled decals propperly globaly per vehicle
  cScripts/cScripts_preInit.sqf
  cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
Labels: T-Enhancement, needs testing

#1015 Updated variable name to let you know its duplication blockers
  cScripts/functions/mission/fn_addEscapeWreck.sqf
  cScripts/functions/mission/fn_addGetOutHelo.sqf
  cScripts/functions/mission/fn_addHaloJump.sqf
  cScripts/functions/mission/fn_addLineJump.sqf
  cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
  cScripts/functions/vehicle/fn_vehicle_addDefaultLoadout.sqf
  cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
  cScripts/functions/vehicle/fn_vehicle_addFunctionsGlobal.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
  cScripts/functions/vehicle/fn_vehicle_addRadio.sqf
  cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf
  cScripts/functions/vehicle/fn_vehicle_applyLoadout.sqf
  cScripts/functions/vehicle/fn_vehicle_reset.sqf
Labels: T-Enhancement, needs testing

#1020 Updated the logging to use the new syntax
  cScripts/cScripts_preInit.sqf
  cScripts/functions/documents/fn_Doc_Radio.sqf
  cScripts/functions/gear/fn_gear_applyCosmetics.sqf
  cScripts/functions/gear/fn_gear_applyLoadout.sqf
  cScripts/functions/gear/fn_gear_loadLoadout.sqf
  cScripts/functions/gear/fn_gear_preInit.sqf
  cScripts/functions/gear/fn_gear_selectLoadout.sqf
  cScripts/functions/gear/fn_gear_setupRadios.sqf
  cScripts/functions/init/fn_init_aceArsenalDefault.sqf
  cScripts/functions/init/fn_init_aceItemReplace.sqf
  cScripts/functions/init/fn_init_aceTagging.sqf
  cScripts/functions/init/fn_init_diary.sqf
  cScripts/functions/init/fn_init_logistics.sqf
  cScripts/functions/init/fn_init_skillAdjustment.sqf
  cScripts/functions/init/fn_init_staging.sqf
  cScripts/functions/init/fn_init_zenModuels.sqf
  cScripts/functions/logistics/fn_createCargoCrate.sqf
  cScripts/functions/logistics/fn_doFieldHospital.sqf
  cScripts/functions/mission/fn_addEscapeWreck.sqf
  cScripts/functions/mission/fn_addGetOutHelo.sqf
  cScripts/functions/mission/fn_addHaloJump.sqf
  cScripts/functions/mission/fn_addLineJump.sqf
  cScripts/functions/mission/fn_addStagingZone.sqf
  cScripts/functions/mission/fn_gate.sqf
  cScripts/functions/mission/fn_teleport.sqf
  cScripts/functions/modules/fn_zenModule_callEndex.sqf
  cScripts/functions/modules/fn_zenModule_resetPlayerRadio.sqf
  cScripts/functions/players/fn_getPlayerName.sqf
  cScripts/functions/players/fn_setActiveRadio.sqf
  cScripts/functions/players/fn_setRadioChannel.sqf
  cScripts/functions/players/fn_setTeamColor.sqf
  cScripts/functions/systems/fn_addInsigniaSelection.sqf
  cScripts/functions/systems/fn_addInsigniaSelectionList.sqf
  cScripts/functions/systems/fn_addLoadoutSelection.sqf
  cScripts/functions/systems/fn_addObjectToCurator.sqf
  cScripts/functions/systems/fn_clearRadioIds.sqf
  cScripts/functions/systems/fn_createVehicleLable.sqf
  cScripts/functions/systems/fn_getArsenalWhitelist.sqf
  cScripts/functions/systems/fn_getChannelName.sqf
  cScripts/functions/systems/fn_getRadioBase.sqf
  cScripts/functions/systems/fn_getUnitArsenalDefault.sqf
  cScripts/functions/systems/fn_isValidFaction.sqf
  cScripts/functions/systems/fn_para_equipment.sqf
  cScripts/functions/systems/fn_setupLoadoutSelection.sqf
  cScripts/functions/vehicle/fn_vehicle_addCosmeticSelection.sqf
  cScripts/functions/vehicle/fn_vehicle_getPylon.sqf
  cScripts/functions/vehicle/fn_vehicle_reset.sqf
  cScripts/functions/vehicle/fn_vehicle_setRadio.sqf
Labels: T-Enhancement, WIP

#1028 TFAR Spectator ability to hear others
  description.ext
Labels: T-Enhancement
