Repository 7Cav/cScripts, pull requests merged in 2024-01, with the labels that each got.

#1074 Added civilian casualtie simulation system
  cScripts/CfgFunctions.hpp
  cScripts/cScripts_postInit.sqf
  cScripts/functions/civ/fn_civ_checkProjectile.sqf
  cScripts/functions/civ/fn_civ_damage.sqf
  cScripts/functions/civ/fn_civ_init.sqf
  cScripts/functions/mission/fn_makeAgent.sqf
Labels: T-Enhancement, needs testing

#1110 Added todo check script this is a valid error. Its just to get them listed
  .github/workflows/testing.yml
  tools/checkTodo.sh
Labels: ignore changelog

#1112 Changed Todo to now exit 0 always
  tools/checkTodo.sh
Labels: ignore changelog

#1107 Improved code with some better syntax
  cScripts/functions/systems/fn_addHeal.sqf
  cScripts/functions/systems/fn_addInsigniaSelection.sqf
  cScripts/functions/systems/fn_addLoadoutSelection.sqf
  cScripts/functions/systems/fn_addReGear.sqf
  cScripts/functions/systems/fn_createActionCategory.sqf
Labels: T-Enhancement, T-Cleanup, needs testing

#1109 Added new KAM items to arsenal and updated cba settings with KAM settings
  cScripts/functions/init/fn_init_logistics.sqf
  cba_settings.sqf
Labels: T-Arsenal & Supplies

#1113 Added stinger crate and updated Stryker inventories
  cScripts/functions/init/fn_init_logistics.sqf
  cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
Labels: T-Arsenal & Supplies

#1114 Fixed Disable Advanced Fatigue
  cba_settings.sqf
Labels: T-Settings

#1115 Fixed Stryker Crew being shown
  cScripts/Loadouts/CfgLoadouts_Bravo_Viking.hpp
Labels: T-Bugfix

#1117 Updated ACE permissions for pilots
  cScripts/Loadouts/CfgLoadouts_Alpha_FixedWing.hpp
  cScripts/Loadouts/CfgLoadouts_Alpha_Rotary.hpp
Labels: T-Loadouts

#1116 Added support of usage of better name "cScripts_Staging_Zone" instead of "zone_staging"
  cScripts/functions/init/fn_init_staging.sqf
Labels: T-Enhancement

#1118 Fixed composition unit being player instead of playable
  Compositions/Cav_Rotary_Aviation/composition.sqe
Labels: T-Bugfix, T-Compositions

#1119 Fixed typo for civilian zone marker names
  cScripts/functions/civ/fn_civ_init.sqf
Labels: T-Bugfix

#1131 Added Adjusted to pr name script
  tools/checkPullRequestTitle.sh
Labels: ignore changelog

#1128 Fixed broken backpacks for all kits and whitelists after the USP update. Added Missing KAM Equipment to Weapons Squad kits.
  cScripts/Loadouts/CfgLoadouts_Alpha.hpp
  cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp
  cScripts/Loadouts/CfgLoadouts_Bravo_Viking.hpp
  cScripts/Loadouts/CfgLoadouts_Charlie_Squad.hpp
  cScripts/Loadouts/CfgLoadouts_Charlie_Weapon.hpp
  cScripts/functions/init/fn_init_logistics.sqf
Labels: T-Loadouts, T-Arsenal & Supplies

#1129 Updated CBA Settings fixing advanced fatigue
  cba_settings.sqf
Labels: T-Settings

#1127 Adjusted all Compositions, Seperated ATLAS into their own making it easier to maintain and get the slotting order correct.
  Compositions/ATLAS_Platoon_vTEST/composition.sqe
  Compositions/ATLAS_Platoon_vTEST/header.sqe
  Compositions/Cav_Bandit_Platoon_Deployment/composition.sqe
  Compositions/Cav_Bandit_Platoon_Deployment/header.sqe
  Compositions/Cav_Misfit_Platoon_Deployment/composition.sqe
  Compositions/Cav_Misfit_Platoon_Deployment/header.sqe
  Compositions/Cav_Stryker_Scout_Platoon/composition.sqe
  Compositions/Cav_Stryker_Scout_Platoon/header.sqe
Labels: T-Compositions

#1124 Removed AT missiles from Strykers
  cScripts/functions/vehicle/fn_vehicle_getPylon.sqf
  cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf
Labels: T-Vehicle
